spring:
  config:
    activate:
      on-profile: oracle-cloud
  datasource:
    username: rixon
    password: wappit-xaVpop-fimqi9
    url: jdbc:oracle:thin:@rixoracloud2023_high?TNS_ADMIN=/Users/rixonmathew/apps/oracle/db_cloud/Wallet_RIXORACLOUD2023
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 10
      max-lifetime: 300000
      pool-name: oracle26ai
      connection-test-query: select 1 from dual
      data-source-properties:
        "[v$session.program]": data-access-tests
      idle-timeout: 120000
  r2dbc:
    username: rixon
    password: wappit-xaVpop-fimqi9
    url: r2dbc:oracle://rixoracloud2023_high
    properties:
      oracle.net.tns_admin: /Users/rixonmathew/apps/oracle/db_cloud/Wallet_RIXORACLOUD2023
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: oracle

server:
  port: 9799

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    level:
      - org.hibernate.SQL: error

---

spring:
  config:
    activate:
      on-profile: oracle-cloud-win
  datasource:
    username: rixon
    password: wappit-xaVpop-fimqi9
    url: jdbc:oracle:thin:@rixoracloud2023_high?TNS_ADMIN=C:\\Users\\rixon\\Wallet_RIXORACLOUD2023
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 50
      minimum-idle: 10
      max-lifetime: 300000
      pool-name: oracle26ai-win
      connection-test-query: select 1 from dual
      data-source-properties:
        "[v$session.program]": data-access-tests
      idle-timeout: 120000
  r2dbc:
    username: rixon
    password: wappit-xaVpop-fimqi9
    url: r2dbc:oracle://rixoracloud2023_high
    properties:
      oracle.net.tns_admin: C:/Users/rixon/Wallet_RIXORACLOUD2023

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: oracle

server:
  port: 9799

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    level:
      - org.hibernate.SQL: error
